### ISSUE TITLE
checksetup.m

### ISSUE THREAD

**Issue by yaseminmb** [prosodylab/prosodylab-experimenter#6]
check whether experiment spreadsheet is ordered by item first, and then by condition, otherwise stop and give an error. (particularly important for experiments with randomization, but could be implemented for all)
check whether all sound files listed in 'contextFile' are actually in folder '3_stimulus'

**Comment by mchlwgnr** [comment]
we're now testing whether soundfiles etc. actually exist (fixed a few months ago)
